### ISSUE TITLE
Make the code open source

### ISSUE THREAD

**Issue by MatadorProBr** [inotia00/VancedMicroG_v2#1]
There is literally no reason to not share the MicroG code

**Comment by inotia00** [comment]
> There is literally no reason to not share the MicroG code

It has little change from the original microg source.

If you wish, you can also release the source of microg.

**Comment by MatadorProBr** [comment]
Well this is what I wanted so I can check the code and see if there is something suspect.
But anyways, thanks and will close this issue.

(also if you can make the repo a fork of the original Vanced microG, it would make more easy to see the changes)
